### ISSUE TITLE
HTML5 and namespace for MathML

### ISSUE THREAD

**Issue by essepuntato** [essepuntato/rash#24]
In HTML, have mathml:math to be associated with the related namespace declaration? See http://www.w3.org/TR/html5-diff/#syntax

**Comment by sideshowbarker** [comment]
Per http://www.w3.org/TR/html/syntax.html#parsing when an HTML parser encounters a start tag whose name is `math` it inserts an `math` element into the DOM in the MathML namespace. So the entire subtree of that element then also automatically gets put into the MathML namespace.

Similarly for any `svg` start tag; the HTML parser puts it into the DOM in the SVG namespace.
