### ISSUE TITLE
Paper on RASH for SePublica 2015

### ISSUE THREAD

**Issue by essepuntato** [essepuntato/rash#30]
Dear Mike,

Some of my colleagues and I have written a first draft of a paper describing the RASH framework to submit to the SePublica 2015 Workshop (http://sepublica.mywikipaper.org/drupal/). You can find the paper in the directory “papers”. Of course, it is written in RASH :-)

I’ve also added you as co-author since your amazing contribution to the framework in the past two weeks. It would be terrific if you could spend a bit of your time in reading the paper and modifying it where you think is appropriate – however I totally understand whether you have not time to dedicate to this task, don’t worry. 

I will work again on the paper only on Monday Mar 15 afternoon (CET time) in order to finalise and submitting it to the workshop.

Thanks in advance for your time.
Have a nice day :-)

S.

**Comment by sideshowbarker** [comment]
Hi @essepuntato Thanks—yes I’ll look through the paper and get back to you by Monday morning your time

**Comment by sideshowbarker** [comment]
Hi @essepuntato I look through the paper and don't have any comments except to say think it’s great and I’m looking forward to hearing about how it’s received.

One note fwiw: While I work for the W3C I'm also a professor at Keio University so feel free to include mention of Keio in the authorship section if you think it helps. Certainly as far as readership here in Japan goes, it might make some readers here a bit more inclined to look further into the paper.

**Comment by essepuntato** [comment]
OK, thanks Mike. I've added also your other affiliation in the new revision I've just committed to the repo.

**Comment by essepuntato** [comment]
Hi all,

First of all, a news: the deadline for submitting the paper to SePublica has changed. The new one is Monday 23rd of March.

As a consequence, I've modified the paper according to several comments received from you in the past few days. I'm just asking you now to read the current version of the paper and to add/modify where you think is more appropriate, preferably before Monday 23rd, in order to be able to finalise the paper before the deadline.

Thanks all of you for your help!
Have a nice day :-)

S.

**Comment by sideshowbarker** [comment]
OK, thanks—will take another look

**Comment by essepuntato** [comment]
The paper was submitted on Tuesday (March 24) at 11:30 CET.
