### ISSUE TITLE
Provide executable rashconvert.jar tool

### ISSUE THREAD

**Issue by sideshowbarker** [essepuntato/rash#31]
We can make the XSLT templates/stylesheets in https://github.com/essepuntato/rash/tree/master/xslt usable even with non-well-formed-XML RASH documents by providing a executable `rashconvert.jar` tool. I can build a self-contained jar file that RASH users can just run from the command-line like this:
```
java -jar rashconvert.jar --template=acm-icps.xsl --html --input=FILE.html --output=ICPS.tex
```
…where, if the `--html` argument is specified, the tool will parse the RASH document using an HTML parser, before transforming it.

Further, we would package up the XSLT templates within the jar itself, such that users would not need to have the stylesheets on their systems; instead they could just do, e.g.:
```
java -jar rashconvert.jar --output=acm-icps --html --input=FILE.html --output=ACM-ICPS.tex
```
Further, if we wanted to, we could make the default behavior be that files with `.html` extensions are automatically parsed as text/html HTML, while files with `.xhtml` extensions are automatically parsed as XML, so that users would then only need to do this:
```
java -jar rashconvert.jar --output=acm-icps --input=FILE.html --output=ACM-ICPS.tex
```

**Comment by essepuntato** [comment]
Hi Mike,
that's a great idea so, please, go ahead. My only concern is to include the XSLT files within the tool at this stage. Just because in the next months I plan to add several additional XSLT to handle such conversion and it is possible that I'll do several commits for fixing bugs. What do you think?

ps: I've assigned this issue directly to you.

**Comment by sideshowbarker** [comment]
> that's a great idea so, please, go ahead. My only concern is to include the XSLT files within the tool at this stage. Just because in the next months I plan to add several additional XSLT to handle such conversion and it is possible that I'll do several commits for fixing bugs.

That's no problem—we can release new versions of the tool with the updated XSLT files included. And we could also add a user option that enables users to manually specify an XSLT file to override the packaged XSLT stuff, if the users want to use a newer version of the stylesheet that we've not yet packaged and re-released in an updated version of the tool.

And we can set up an automated build that will regenerate a new jar every time any changes are made to  the XSLT files.

**Comment by essepuntato** [comment]
BTW, I've added a directory "sources" in the main dir of the repo where we all can put the source codes of our applications. Of course the actual tools developed (JAR files, scripts, etc.) should be placed in the directory "tools".

**Comment by essepuntato** [comment]
In addition to the direct conversion of the RASH file into LaTeX, another feature that could be good for a tool like this is to create a new directory containing the LaTeX *with* the related .cls file and the pictures used in the RASH document. In this way we would be able to offer to the user the directory containing all the object that are necessary for building the PDF from the LaTeX file.

However, while the relation between the transforming XSLT and the .cls file can be provided in a configuration file, the picture related with the RASH document should be taken by looking to the attribute @src of the element "img".

**Comment by sideshowbarker** [comment]
Closing this as I have no plans to work it on myself at this point. Of course feel free to re-open it (e.g., if somebody else plans to work on this).
