### ISSUE TITLE
Support em and strong as well as i and b

### ISSUE THREAD

**Issue by npdoty** [essepuntato/rash#49]
The documentation suggests that `<i>` and `<b>` tags are allowed. Instead, shouldn't we prefer the usage of `<em>` and `<strong>`? Or if there's some reason that `i` and `b` need to be supported, it would be good to document that `em` and `strong` are allowed, with an equivalent semantic interpretation.

**Comment by sideshowbarker** [comment]
`i` and `b` are valid elements in the current HTML Recommendation/standard (HTML5), with documented meanings that are appropriate to use in RASH. They are not deprecated in any way in current HTML (HTML5), or considered bad practice. But I think it would be ok to document that people can use  `em` and `strong` instead if they prefer to use them.

**Comment by npdoty** [comment]
Thanks, Mike, I definitely didn't or shouldn't have implied that `i` and `b` are deprecated. (I think since the documentation describes them as different levels of general emphasis that there are reasons to prefer `em` and `strong`, but I'd happily change my request to support them as equivalent.)

**Comment by sideshowbarker** [comment]
Yeah I don’t think any docs anywhere should say that there absolute reasons to prefer use of `i` and `b` over `em` and `strong` (since all are legitimately part of the HTML language, with meanings/uses well-defined in the HTML spec).

**Comment by essepuntato** [comment]
The new version of RASH, we decided to keep only "i" and "b". The idea is that we would like to avoid two elements for expressing the same semantics.
