### ISSUE TITLE
Adding blocks only for the web-based view

### ISSUE THREAD

**Issue by pietercolpaert** [essepuntato/rash#63]
I'm working on a demo paper and I would like to include examples of the demo in the text in the web-based view, but this should not be part of the LNCS proceedings. Is there a way to add a class to skip a block it in the non-web-based views?

**Comment by essepuntato** [comment]
Hi Pieter,

Sorry for the late answer. There is no a builtin method for doing that in the RASH Framework. However, an option would be to modify the CSS files referenced in your RASH paper by adding a rule like:

<pre>
@media print {
    .noprint {
        display:none;
    }
}
</pre>

and then to set the attribute "class" of the HTML elements you don't want to visualise in print format to "noprint", e.g.:

<pre>
&lt;p&gt;This will be visualised always.&lt;/p>
&lt;p class="noprint"&gt;This won't be visualised when printing the article.&lt;/p&gt;
</pre>

Does this solve your problem?

**Comment by pietercolpaert** [comment]
It does and thanks for your answer! I solved it like this since I asked the question. Still wondered whether this was considered "okay" within RASH as the HTML version will contain slightly different content than the PDF :)

**Comment by essepuntato** [comment]
Well, it is a totally-acceptable RASH paper to me. I don't really know, however, what the chairs of the demo track you are submitting it may think about this dynamic cut :-)
