### ISSUE TITLE
Avoiding editing of immutable objects

### ISSUE THREAD

**Issue by essepuntato** [essepuntato/rash#88]
The content of some of the objects visualised by "rash.js" (cross-ref, section numbering, etc.) cannot be modified by the user.

**Comment by gspinaci** [comment]
**Update**

Caption of figures are added as non editable objects, using contenteditable=false.
In this case captions are not editable but they are removeable.

**Comment by gspinaci** [comment]
**Proposal**

Probably another way is to mark every "immutable" objects (captions, section[role]>h1) with a label like **data-immutable**, and call a function to transform them into a not editable and not removeable element (but also selecteable).

**Comment by gspinaci** [comment]
**Todo**

Understand how and why backspace press is blocked before a immutable reference.
This happens with crossreferences pointing to bliblioentries
