### ISSUE TITLE
Exit from inline elements pressing enter key

### ISSUE THREAD

**Issue by gspinaci** [essepuntato/rash#95]
Using TinyMCE pressing enter key inside an inline element like code, the caret must be moved outside the element

**Comment by essepuntato** [comment]
Just be aware of the use of `code` within the `pre` element. In this case, pressing the enter key must result in a normal carriage return.

**Comment by gspinaci** [comment]
So, every **inline** elements are "completed" by clicking a second time the right button? E.g. pressing **inline code** add the `code` element inside a `p`, pressing the button again, the caret shift after the `code` element.

**Comment by gspinaci** [comment]
Using text nodes this issue is complete.

e.g.
Pressing enter on inline_code, the cursor is moved at the start of the next text node.
